version: "3"
services:
  hapi-fhir-jpaserver-start:
    build: .
    container_name: hapi-fhir-jpaserver-start
    restart: on-failure
    ports:
      - "8080:8080"

  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
        - "5432:5432"
    environment:
        POSTGRES_USER: "UserName"
        POSTGRES_PASSWORD: "Password"
